DEFAULT_ANDROID_SDK_ROOT = /home/runner/.android/sdk
DEFAULT_ANDROID_NDK_ROOT = /home/runner/.android/sdk/ndk/29.0.13599879
DEFAULT_ANDROID_PLATFORM = android-21
DEFAULT_ANDROID_NDK_HOST = linux-x86_64
DEFAULT_ANDROID_ABIS = armeabi-v7a arm64-v8a
ANDROID_JAVAC_TARGET_VERSION = 
ANDROID_JAVAC_SOURCE_VERSION = 
GCC_MACHINE_DUMP = 
