DEFAULT_ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
DEFAULT_ANDROID_NDK_ROOT = /Users/runner/Library/Android/sdk/ndk/29.0.13599879
DEFAULT_ANDROID_PLATFORM = android-21
DEFAULT_ANDROID_NDK_HOST = darwin-x86_64
DEFAULT_ANDROID_ABIS = armeabi-v7a arm64-v8a
ANDROID_JAVAC_TARGET_VERSION = 
ANDROID_JAVAC_SOURCE_VERSION = 
GCC_MACHINE_DUMP = 
